version: '3.7'

services:
  postgres:
    container_name: topline_postgres
    image: postgres:14
    ports:
      - 5555:5432
    environment:
      - 'POSTGRES_PASSWORD=local'
      - 'POSTGRES_USER=local'
      - 'POSTGRES_DB=interview'
